### ISSUE TITLE
Ex 2 Task 6: Online migration activity fails

### ISSUE THREAD

**Issue by ac2707** [microsoft/MCW-Migrating-SQL-databases-to-Azure#4] opened 2019-08-12 10:51 UTC
Error below:

Error Detail
A scenario reported an unknown error. 
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

![image](https://user-images.githubusercontent.com/49182510/62860264-415fa800-bd1d-11e9-8c5c-de905ee1ae24.png)

Please advise

**Comment by kylebunting** [comment] 2019-08-22 17:45
@ac2707, I've run through the online migration twice, and have not been able to reproduce the issue you are reporting. The error you are receiving makes me think that maybe there is an issue with the network security group associated with your SQL MI instance. I've updated the ARM template used to create the resources due to an issue there, so perhaps you could run the ARM template and try again?

**Comment by kylebunting** [comment] 2019-08-26 12:36
I tested this a third time over the weekend, and it appears to be working properly. Closing this issue. @ac2707, please reopen this issue if you still continue to experience issues.

**Closed by kylebunting** 2019-08-26 12:36 UTC
